### ISSUE TITLE
Next "[proposal's name]" button

### ISSUE THREAD

**Issue by MMDasa** [advaita-krishna-das/gbc-meeting#149]
Как будет выглядеть кнопка Next "[proposal's name]", если название законопроекта очень длинное? Есть ли способ ограничить размеры воспроизводимого в кнопке названия 10-15 знаками?

**Comment by akdasa** [comment]
Вынес подпись под кнопки (чтобы размер кнопки не менялся из-за надписи, что не очень красиво). А сами кнопки переделал в соответствии с комментариями Алексея.

![image](https://user-images.githubusercontent.com/22368151/35763374-11dab7e8-08d1-11e8-9d65-927adf33ad2d.png)
